theme: minima
title: 萌萌的ai学习小站·2CutesAILearningNote 
author: 萌萌 aka 2cute
description: 记录我的AI学习路线，分享AI入门教程、技术心得
url: "https://2ccutes.top/"

plugins:
  - jekyll-seo-tag
future: true

# paginate: 5  # 每页显示的文章数
# paginate_path: "/blog/page:num"  # 分页路径
