theme: minima
title: 2CutesAILearningNote
author: 萌萌 aka 2cute
description: 记录我的AI学习历程，分享技术心得
url: "https://2ccute.github.io/2cutesailearningnote/"
plugins:
  - jekyll-seo-tag

paginate: 9  # 每页显示的文章数
paginate_path: "/blog/page:num"  # 分页路径

